branches:
  only:
  - master
language: node_js
node_js:
- '7'
script:
- ng build --prod --aot
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules

before_deploy:
  - npm install firebase-tools

after_success:
  - firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --non-interactive --only hosting
