branches:
  only:
  - master
language: node_js
node_js:
- '7'
script:
- ng build --prod --aot
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_DEPLOY_TOKEN
