branches:
  only:
  - master
language: node_js
node_js:
- '7'
script:
  - npm build
matrix:
  fast_finish: true
cache:
  directories:
    - node_modules
deploy:
  provider: firebase
  token:
    secure: WqOJHwoO0a/021e8z3w5Evy1WbqxtHWZgHKSbazBTjQvUh1/X5X/JRBjWBaSZxsklL0tzrBORlDUmBVrMkzdbSn6r4qSHESFykS3821+PCuC94HASCuyc/QSaaIUH1Z5IrxAzt0Nc/c6TfHyElUzRK4NljPOp41cMeUU+2xDdzGE0FTxi3uIQnQYAoOZ/PifdrN+1XMUTaAvt5E3uw9xkgRy5OXk3IUhtJ0eGUQh6fdlZC+VzsX1N67Mb7wrAVqYXaIty0BvCzfsX/vKl0CGfEVnOSs7pFrD0pWnJy0u38gVKkcC4b4d8oOD0xR2OhF7hnUdB4sCpu6CAp2Icq02YPSNxVaBGjnWLsAwpIxZdm0GFkXXvBnktIz8Hh6KfNdd2rp46iMVHi9Y/Jf8gicTjU7J1DPNo6HFOk8lq5sKMRWMvQ0wRN2mNoIlQt7crqm277YdxU8wiT2VRnqIJF/tmNiDR8eNOrq5zHuQBrLDqIeHijtWER1fovotjaQDAlV9UjB6SMntoc08k34WBAlAXGcshOx2NTCgmm/kwElvPY4A5Qofv+2+1VV1XpmmXAU1C5tDqEdNSqcym4xOCJ9kjoGP3v42UcduaRMXj9eYNAjij2po+yP9Whgd90EiwWkYE9ofg6hAwqzYIsZZEc7bn4IAzFntiOjr47wBUrhF4cA=
