branches:
  only:
  - master
language: node_js
node_js:
- '7'
install:
  - npm install
  - npm install -g firebase-tools
script:
- ng build --prod --aot
matrix:
  fast_finish: true
cache:
  directories:
  - node_modules
after_success:
  - firebase deploy --token "$FIREBASE_DEPLOY_TOKEN" --non-interactive --only hosting
